version: '3.7'

services:
  bot:
    container_name: crypto-trading-bot
    image: hdthuan/crypto-trading-bot-image
    build:
        context: .
        dockerfile: Dockerfile.dev
    volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
    ports:
        - "8080:8080"
    command: npm start
